config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  	get '/', to: 'static#home', as: 'root'

	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'

	get    '/login',   to: 'sessions#new'
  	post   '/login',   to: 'sessions#create'
  	delete '/logout',  to: 'sessions#destroy'
	
	resources :users
	resources :gossips do
		resources :comments, only: [:create, :destroy]
		resources :likes, only: [:create, :destroy]
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commenter, class_name: 'User'
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :author, class_name: 'User'
#  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :liker, class_name: 'User'
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
	has_many :comments, :class_name => 'Comment', :foreign_key => 'commenter_id'
	has_many :likes, :class_name => 'Liker', :foreign_key => 'liker_id'
	has_many :gossips, :class_name => 'Gossip', :foreign_key => 'author_id'

	validates :name, presence: true, length: { maximum: 50 }
	
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                    format: { with: VALID_EMAIL_REGEX },
	                    uniqueness: { case_sensitive: false }
	
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	include SessionsHelper
	@@visitors = 0
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_gossip
  before_action :set_comment, only: [:destroy]

  	def create
  		Comment.create!(comment_params)
      redirect_back(fallback_location: gossips_path)
  	end

  	def destroy
  		@comment.destroy
      redirect_back(fallback_location: gossips_path)
  	end

	private
    # Use callbacks to share common setup or constraints between actions.
	def set_gossip
		@gossip = Gossip.find(params['gossip_id'])
	end
	def set_comment
  	@comment = Comment.find(params['id'])
	end

  def comment_params
    params.require(:comment).permit(:content, :commenter_id, :gossip_id)
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]

  # GET /gossips
  # GET /gossips.json
  def index
    @gossip_selection = Gossip.all
  end

  # GET /gossips/1
  def show
    @comment = Comment.new
    @comment_selection = @gossip.comments
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
  end

  # GET /gossips/1/edit
  def edit
  end

  # POST /gossips
  def create
    puts gossip_params
    @gossip = Gossip.create(gossip_params)
    redirect_to gossip_path(@gossip)
  end

  # PATCH/PUT /gossips/1
  # PATCH/PUT /gossips/1.json
  def update
    @gossip.update(gossip_params)
    redirect_to gossip_path(@gossip)
  end

  # DELETE /gossips/1
  # DELETE /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: 'Gossip was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gossip_params
      params.require(:gossip).permit(:content, :author_id, :anonymous)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_gossip

  	def create
  		#contrôler uniqueness
		like = Like.create(
			gossip_id: @gossip.id,
			liker_id: User.find(rand(User.first.id..User.last.id)).id
		)
	    redirect_back(fallback_location: gossips_path)

	end

	def delete
	end

	private

	def set_gossip
  		@gossip = Gossip.find(params[:gossip_id])
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  	
  	def new
  	end

  	def create
  		user = User.find_by(email: session_params[:email])
    	if user
    		if user.authenticate(session_params[:password])
    			log_in(user)
    			redirect_to user_path(user.id)
    		else
    			flash.now[:danger] = 'Mot de passe incorrect'
				  render 'new'
    		end
	    else
			flash.now[:danger] = 'Aucun utilisateur enregistré avec cet email'
			render 'new'
		end
	end

	def destroy
	    session.delete(:user_id)
		@current_user = nil
		redirect_to root_path
	end


	private
    # Use callbacks to share common setup or constraints between actions.
    
	def session_params
    	params.require(:session).permit(:email, :password)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  	@gossip_selection = Gossip.last(3)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update]
  # GET /users/1
  # GET /users/1.json
  def show
    if current_user == @user
      @comment_selection = @user.comments
      @gossip_selection = @user.gossips
    elsif logged_in?
      flash[:danger] = "Vous ne pouvez pas accéder à ce compte !"
      redirect_to user_path(current_user)
    else 
      redirect_to login_path
    end
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Vous êtes maintenant connecté !"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 	def log_in(user)
    	session[:user_id] = user.id
  	end

  	def current_user
  		if session[:user_id]
      		@current_user ||= User.find_by(id: session[:user_id])
  		end
	end

  	def logged_in?
  		puts current_user
    	!current_user.nil?
  	end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment-form.html.erb
<div class='form'>
	<%= form_for :comment, method: 'create', url: @gossip.id.to_s+'/comments', :authenticity_token => true, class:'form' do |f| %>
		<%= f.text_area :content, placeholder: 'Votre commentaire ici', :required => 'required', class:"form-control col-10" %><br />
		<%= f.hidden_field :commenter_id, value: User.find(rand(User.first.id..User.last.id)).id %>
		<%= f.hidden_field :gossip_id, value: @gossip.id  %>
		<%= f.submit 'Publier votre commentaire', class: 'form-group m-auto btn btn-info'%>
	<% end %>
</div>

app/views/comments/_comment-index.html.erb
<% @comment_selection.each_with_index do |c, i| %>
<% if i % 3 == 0 %>
  <div class='index'>
<% end %>

    <div class= 'card'>
      <div class="card-header">
        <%= c.gossip_id %>
      </div>

      <div class="card-body">
        <%= c.content %>
      </div>

      <div class="card-caption">
        Posté il y 2 jours<% if c.commenter != 'anonymous' %>, par <%= c.commenter.name %><% end %>
      </div>

      <% if current_user.id == c.commenter_id %>
        <div class="card-buttons">
          <li class='btn delete-btn'> <%= link_to gossip_comment_path(c.id), method: :delete, data: { confirm: 'Êtes-vous certain de vouloir supprimer ce commentaire?' } do %>
            <i class="fas fa-trash-alt"></i>
            <% end %>
          </li>
        </div>
      <% end %>
    </div>

  <% if i % 3 == 2 %>
    </div>
  <% end %>
<% end %> 

app/views/gossips/_create-form.html.erb
<div class='card'>
	<%= form_for :gossip,  url: { action: 'create', controller: 'gossips'}, :authenticity_token => true do |f| %>
	<div class='card-body'>
  	<h5>Balance ta rumeur</h5><br/>
  	<%= f.text_area :content, class:"", :required => 'required'%>
  	</div>
	<div class='card-caption'>
  	Souhaitez-vous publier en restant anonyme ?<%= f.check_box :anonymous, class:"form-control" %>
  	</div>
  	<%= f.hidden_field :author_id, value: current_user.id %>
</div>

  	<%= f.submit 'Créer cette rumeur' , class: 'btn'%>
<% end %>

app/views/gossips/_edit-form.html.erb
<%= form_for :gossip, method: 'patch', url: { action: 'update'} do |f| %>
  Balance ta rumeur<%= f.text_area :content, value: @gossip.content, class:"form-control"%><br />
  <div class='form-group form-check row text-center'>
  	<%= f.check_box :anonymous, value: 1, class:"" %>
  	Souhaitez-vous publier en restant anonyme ?
  </div>
  <%= f.hidden_field :author_id, value: @gossip.author_id %>
  <%= f.hidden_field :id, value: @gossip.id  %>
  <div class= 'form-group text-center'>
	  <%= f.submit 'Enregistrer cette rumeur' , class:'btn btn-info'%>
	</div>
<% end %>

app/views/gossips/_gossip-index.html.erb
<% @gossip_selection.each_with_index do |g, i| %>
  <% if i % 3 == 0 %>
    <div class='index'>
  <% end %>

  <section class="card">
    <div class="card-header">
      <div class='card-title'>Rumeur n°<%= g.id %></div>
      <div class='card-metrics'>
        <a href="<%= gossip_path(g.id) %>"><i class="fas fa-comments"></i>  <%= g.comments.count %> </a></a>
        
        <a data-method="create" href="<%= gossip_likes_path(g.id) %>"> <i class="fas fa-thumbs-up"></i>  <%= g.likes.count %></a>
      </div>
    </div>

    <div class="card-body">
      <p class="card-text"> <%= g.content %> </p>
    </div>

    <div class="card-caption">
      Postée il y <%= pluralize(((Time.now - g.created_at)/(3600*24)).to_i, 'jour') %><% if g.anonymous == 0 %>, par <%= g.author.name %><% end %>
    </div>

     <% if current_user.id == g.author_id %>
        <div class="card-buttons">
          <li class='btn modification-btn'> <%= link_to edit_gossip_path(g.id) do %>
            <i class="fas fa-pen"></i>
            <% end %>
          </li>
          <li class='btn delete-btn'> <%= link_to gossip_path(g.id), method: :delete, data: { confirm: 'Êtes-vous certain de vouloir supprimer ce commentaire?' } do %>
            <i class="fas fa-trash-alt"></i>
            <% end %>
          </li>
        </div>
      <% end %>

  </section>

  <% if i % 3 == 2 %>
    </div>
  <% end %>
<% end %>

app/views/gossips/edit.html.erb
<h3>Modification de la rumeur n°<%= @gossip.id %></h3>

<div class= 'offset-3 col-6'>
	<%= render 'edit-form', gossip: @gossip %>
</div>

app/views/gossips/index.html.erb
<%= render 'gossip-index', gossip: @gossip %>

app/views/gossips/new.html.erb
<%= render 'create-form', gossip: @gossip %>

app/views/gossips/show.html.erb
  <section class="card">
    <div class="card-header">
      <div class='card-title'>Rumeur n°<%= @gossip.id %></div>
      <div class='card-like'>
        <a data-method="create" href="<%= gossip_likes_path(@gossip.id) %>"> <i class="fas fa-thumbs-up"></i>  <%= @gossip.likes.count %>
        </a>
      </div>
    </div>

    <div class="card-body">
      <p class="card-text"> <%= @gossip.content %> </p>
    </div>

    <div class="card-caption">
      Postée il y <%= pluralize(((Time.now - @gossip.created_at)/(3600*24)).to_i, 'jour') %><% if @gossip.anonymous == 0 %>, par <%= @gossip.author.name %><% end %>
    </div>

     <% if current_user.id = @gossip.author_id %>

    <div class="card-buttons">
      <li class='btn modification-btn'> <%= link_to edit_gossip_path(@gossip.id) do %>
        <i class="fas fa-pen"></i>
        <% end %>
      </li>
      <li class='btn delete-btn'> <%= link_to gossip_path(@gossip.id), method: :delete, data: { confirm: 'Êtes-vous certain de vouloir supprimer cette rumeur?' } do %>
        <i class="fas fa-trash-alt"></i>
        <% end %>
      </li>
    </div>
    <% end %>


</section>

  <div>
    <%= render 'comments/comment-index' %>
  </div>
  <div>
    <%= render 'comments/comment-form' %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

<!--   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
-->

  </head>

  <body>
    <div class="page-top" >
      <header class='header'>
        <%= render "static/header" %>
      </header>

      <div class="page-contents">
        <% if flash[:info]%>
          <p class="alert alert-info"><%=flash[:info]%></p>
        <% elsif flash[:danger]%>
          <p class="alert alert-danger"><%=flash[:danger]%></p>
        <% elsif flash[:success]%>
          <p class="alert alert-success"><%=flash[:success]%></p>
        <% end%>
    
        <%= yield %>

      </div> 
    </div> 


    <footer>
      <%= render "static/footer" %>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for :user, url: signup_path do |f| %>
  <%= f.text_field :email, placeholder: 'Email', :required => 'required', class:"form-control" %><br />
  <%= f.text_field :name, placeholder: "Nom d'utilisateur", :required => 'required', class:"form-control" %><br />
  <%= f.password_field :password, placeholder: 'Mot de passe', :required => 'required', class:"form-control" %><br />  
  <%= f.password_field :password_confirmation, placeholder: 'Confirmation', :required => 'required', class:"form-control" %><br />
  <%= f.submit 'Valider mon inscription', class: 'form-group m-auto btn btn-info'%>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class='offset-4 col-4 text-center'>
	<%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<section class='tabs'>
	<nav class='profile-info-header'>
		<li>Vos informations</li>
		<li class='modification-tab'> <%= link_to edit_user_path(@user.id)  do %>
			<i class="fas fa-pen"></i>
 			<% end %>
 		</li>
	</nav>
	<div class='cards-container'>
		<p>Votre nom d'utilisateur : <%= @user.name %></p>
		<p>Votre email : <%= @user.email %> </p>
	</div>
</section>

<section class='tabs'>
	<nav>
		<li><%= link_to 'Vos gossips', '#gossips' %></li>
		<li><%= link_to 'Vos comentaires', '#comments' %></li>
		<li><%= link_to 'Vos likes', '#likes' %></li>
	</nav>
	<div class='cards-container'>
		<div class='cards'>
			<div id='gossips'><%= render 'gossips/gossip-index' %></div>
			<div id='comments'><%= render 'comments/comment-index'%></div>
			<div id='likes'></div>
		</div>
	</div>
</section>